### ISSUE TITLE
Implementasi input form sanitization untuk mencegah SQL Injection atau Cross-Site Scripting

### ISSUE THREAD

**Issue by yehezkieldio** [RaihanNih/LoginForm#1]
Referensi
- https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Login.views.php#L13-L21
- https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Register.views.php#L11-L28

**Comment by shelzn** [comment]
> Referensi
> 
>     * https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Login.views.php#L13-L21
> 
>     * https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Register.views.php#L11-L28

https://github.com/RaihanNih/LoginForm/commit/dd2dcd84985c5592130466bd57238b1f24d7d333
Menurutmu?

**Comment by yehezkieldio** [comment]
> > Referensi
> > ```
> > * https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Login.views.php#L13-L21
> > 
> > * https://github.com/RaihanNih/LoginForm/blob/master/src/Views/Register.views.php#L11-L28
> > ```
> 
> [dd2dcd8](https://github.com/RaihanNih/LoginForm/commit/dd2dcd84985c5592130466bd57238b1f24d7d333) Menurutmu?

bolehlah
